version: "3"

services:
  app:
    build: .
    container_name: python
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "80:80"
